# Generated by Django 3.2.9 on 2022-05-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location1', models.CharField(max_length=600)),
                ('location2', models.CharField(max_length=600)),
                ('description', models.CharField(max_length=900)),
                ('date', models.DateField(max_length=300)),
                ('time', models.TimeField(max_length=300)),
                ('severity', models.CharField(max_length=300)),
                ('cause', models.CharField(max_length=900)),
                ('actions', models.CharField(max_length=900)),
                ('type_env', models.BooleanField(default=False, verbose_name='Environmental Incident')),
                ('type_inju', models.BooleanField(default=False, verbose_name='injury/Illness')),
                ('type_property', models.BooleanField(default=False, verbose_name='Property Damage')),
                ('type_vehicle', models.BooleanField(default=False, verbose_name='Vehicle')),
                ('submitted', models.BooleanField(default=False)),
                ('reported_by', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=300)),
            ],
        ),
    ]
