# Generated by Django 3.2.9 on 2022-05-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_auto_20220522_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AlterField(
            model_name='incident',
            name='reported_by',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type_env',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type_inju',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type_property',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type_vehicle',
            field=models.CharField(max_length=200),
        ),
    ]
