# Generated by Django 3.2.9 on 2022-05-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_auto_20220522_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='submitted',
            field=models.CharField(default='f', max_length=200),
        ),
        migrations.AlterField(
            model_name='incident',
            name='reported_by',
            field=models.CharField(max_length=900),
        ),
    ]
